# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-09 22:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='Article',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
    ]
