# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0002_auto_20190609_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(),
        ),
    ]
